#include: package:flutter_lints/flutter.yaml

rules:
  #prefer_const_constructors: false
  #avoid_print: false
  #prefer_typing_uninitialized_variables: false
  #prefer_const_constructors_in_immutables: false

  prefer_const_constructors: false
  prefer_final_fields: false
  use_key_in_widget_constructors: false
  prefer_const_literals_to_create_immutables: false
  prefer_const_constructors_in_immutables: false
  avoid_print: false
