name: reafy_front
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^0.22.0
  introduction_screen: ^3.1.12
  carousel_slider: ^4.2.1
  bubble: ^1.2.1
  kakao_flutter_sdk_user: ^1.6.1
  http: ^1.1.0
  provider: ^5.0.0
  flutter_slidable: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 500
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
