name: reafy_front
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.9
  introduction_screen: ^3.1.12
  dio: ^5.4.0
  path: ^1.8.0

  kakao_flutter_sdk_user: ^1.9.0
  http: ^1.1.0
  provider: ^5.0.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.6
  lottie: ^2.2.0
  flutter_spinkit: ^5.1.0
  tutorial_coach_mark: ^1.2.11
  showcaseview: ^2.1.1

  expandable_text: ^2.2.0
  timeago: ^3.2.2
  cached_network_image: ^3.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.0.18
  flutter_image_compress: ^2.1.0

  flutter_dotenv: ^5.0.2
  dotted_border: ^2.1.0
  fl_chart: ^0.66.2
  url_launcher: ^6.2.3
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#63b865"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/items/
    - assets/images/progress/
    - assets/svg/
    - assets/fonts/
    - .env
    - assets/lottie/

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 500
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
